<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ch_sb_blog"
 *
 * Auto generated by Extension Builder 2016-01-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Blog Christophe & Stéphane',
	'description' => '',
	'category' => 'plugin',
	'author' => 'BOURDIER Stéphane, HOARAU Christophe',
	'author_email' => 'steph63b@hotmail.fr, chris.hoarau@hotmail.fr',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);